export const EstFac = {
  title: "Estetica Faciala",
  serviceName: [
    "Consultatie specialist",
    "Volumizare si conturare buze cu acid hialuronic",
  ],
  servicePrice: ["Gratuit", "200€"],
};

export const Profilaxie = {
  title: "Profilaxie",
  serviceName: [
    "Fluorizare in cabinet - ambele arcade",
    "Detartraj cu ultrasunete periaj profesional airflow",
    "Periaj profesional",
    "Igienizare cu air-flow (prophy-jet ambele arcade)",
    "Sigilare dinti definitivi (profilaxia cariei dentare)",
    "Gutiera bruxism",
  ],
  servicePrice: [
    "100 Lei",
    "150 Lei",
    "50 Lei",
    "100 Lei",
    "100 Lei",
    "300 Lei",
  ],
};

export const Plombe = {
  title: "Plombe",
  serviceName: [
    "Indepartare obturatie veche",
    "Obturatie (plomba) medie de compozit fotopolimerizabil",
    "Obturatie (plomba) mare compozit fotopolimerizabila (carie profunda)",
    "Obturatie la nivelul stratului profund al dentinei",
    "Obturatie glassionomer mediu",
    "Obturatie glassionomer mare",
    "Obturatie estetica",
    "Fateta directa din compozit in cabinet",
  ],
  servicePrice: [
    "40 Lei",
    "100 Lei",
    "150 Lei",
    "210 Lei",
    "50 Lei",
    "80 Lei",
    "170 Lei",
    "300 Lei",
  ],
};

export const TratEndodontic = {
  title: "Tratament Endodontic",
  serviceName: [
    "Tratament endodontic dinti monoradiculari (incisivi, canini)",
    "Tratament endodontic dinti pluriradiculari (premolari, molari)",
    "Retratament endodontic - dinti monoradiculari",
    "Retratament endodontic - dinti pluriradiculari",
    "Drenaj endodontic ( include anestezie, drenaj endodontic, spalaturi cu solutie antiseptica)",
    "Incizie abces dentar (anestezie, incizie abces, spalaturi) si drenaj endodontic",
    "Indepartare corp strain (ace rupte) de pe canal",
    "Spalaturi",
  ],
  servicePrice: [
    "350 Lei",
    "400 Lei",
    "400 Lei",
    "450 Lei",
    "50 Lei",
    "100 Lei",
    "100 Lei",
    "50 Lei",
  ],
};

export const TratProtetic = {
  title: "Tratament Protetic",
  serviceName: [
    "Proteza totala acrilica / arcada",
    "Ablatie coroana (indepartarea unei coroane vechi)/element",
    "Ablatie pivot turnat de pe canal",
    "Coroana provizorie din acrilat (laborator)",
    "Coroana provizorie in cabinet",
    "Coroana metalo-ceramica semifizionomica (Weisser)",
    "Coroana metalo-ceramica total fizionomica",
    "Coroana ceramica pe suport zirconiu",
    "Coroana integral ceramica",
    "Coroana E-max pentru molari si premolari",
    "Coroana E-max cu placare ceramica pentru frontali",
    "Coroana ceramica pe zirconiu pe implant",
    "Pivot metalic turnat",
    "Pivot fibra de sticla",
    "Cimentare cu galssionomer (se taxeaza numai daca nu este executata in cadrul cabinetului)",
    "Proteza partiala sau totala acrilica cu dinti din acrilat",
    "Proteza Kemeny",
    "Proteza flexibila",
    "Proteza scheletata cu sisteme speciale",
    "Captusire proteza acrilica",
    "Inlocuire dinte in proteza",
    "Reparatie proteza/croset",
    "Wax – up / dinte",
  ],
  servicePrice: [
    "1000 Lei",
    "40 Lei",
    "80 Lei",
    "200 Lei",
    "70 Lei",
    "350 Lei",
    "500 Lei",
    "1000 Lei",
    "1200 Lei",
    "1200 Lei",
    "1500 Lei",
    "300 Euro",
    "150 Lei",
    "200 Lei",
    "40 Lei",
    "1000 Lei",
    "250 Lei",
    "1500 Lei",
    "2500 Lei",
    "150 Lei",
    "70 Lei",
    "150 Lei",
    "100 Lei",
  ],
};

export const TratChirurgical = {
  title: "Tratament Chirurgical",
  serviceName: [
    "Anestezie prin infiltratie",
    "Drenaj abces vestibular",
    "Extractie dinte monoradicular",
    "Extractie dinte pluriradicular",
    "Extractie dinte paradontotic",
    "Extractie cu alveolotomie monoradicular",
    "Extractie cu alveolotomie pluriradicular",
    "Sutura chirurgicala",
    "Tratament hemoragie / alveolita postextractiona",
    "Extractie molar de minte inclus",
    "Extractie molar de minte erupt",
    "Extractie molar de minte semi-inclus",
    "Inchidere comunicare orosinusala",
    "Regularizare de creasta",
    "Chistectomie (include extractie)",
    "Decapusonare molar de minte",
    "Coroana provizorie pe implant",
    "Frenectomie",
    "Rezectie apicala incisivi, canini, premolari superiori",
    "Rezectie apicala premolari inferiori, molari",
    "Extirpare tumora mucoasa orala",
    "Gingivectomie cu bisturiu/dinte",
    "Gingivectomie cu laser/dinte",
    "Chiuretaj alveolar",
    "Descoperire canin inclus",
    "Gelaspon",
  ],
  servicePrice: [
    "20 Lei",
    "100 Lei",
    "100 Lei",
    "150 Lei",
    "70 Lei",
    "210 Lei",
    "300 Lei",
    "10 Lei",
    "50 Lei",
    "450-600 Lei",
    "250 Lei",
    "350 Lei",
    "150 Lei",
    "150 Lei",
    "400-600 Lei",
    "70 Lei",
    "200 Lei",
    "300 Lei",
    "350 Lei",
    "400 Lei",
    "300 Lei",
    "100 Lei",
    "150 Lei",
    "40 Lei",
    "300 Lei",
    "20 Lei",
  ],
};

export const EstDentara = {
  title: "Estetica Dentara",
  serviceName: [
    "Albire dentara in cabinet",
    "Fatete laminate (ceramica presata e-max)",
    "Bijuterie dentara",
    "Mock-up / dinte",
  ],
  servicePrice: ["450 Lei", "1800 Lei", "150 Lei", "70 Lei"],
};

export const Ortodontie = {
  title: "Ortodontie",
  serviceName: [
    "Aparat dentar mobil ( pentru copiii ce prezinta dinti temporari)",
    "Activare aparat metalic/ceramic/safir/arcada",
    "Control aparat mobil/arcada",
    "Control contentie/arcada",
    "Reparatie aparat mobil in laborator",
    "Aparat functional trainer",
    "Monobloc, activator simplu",
    "Aparat dentar metalic / 1 arcada",
    "Aparat dentar Safir / 1 arcada",
    "Aparat dentar ceramic / 1 arcada",
    "Recolare bracket metalic / ceramic / safir",
    "Recimentare inel",
    "Aparat dentar Damon metalic autoligaturant",
    "Aparat dentar Damon fizionomic (transparent)",
    "Contentie (retainer fix sau gutiera)/arcada",
    "Indepartare aparat dentar (include detartraj si periaj)/arcada",
    "Disjunctor",
    "Arc transpalatinal",
    "Ortoimplant",
    "Mentinator spatiu fix",
    "Mentinator spatiu mobil",
    "Inlocuire arc fizionomic (la cerere)",
  ],
  servicePrice: [
    "1400 Lei",
    "100 Lei",
    "50 Lei",
    "50 Lei",
    "50 Lei",
    "800 Lei",
    "1200 Lei",
    "1200 Lei",
    "2500 Lei",
    "2500 Lei",
    "50 Lei",
    "50 Lei",
    "---- Lei",
    "---- Lei",
    "150 Lei",
    "300 Lei",
    "1200 Lei",
    "300 Lei",
    "500 Lei",
    "200 Lei",
    "300 Lei",
    "60 Lei",
  ],
};
